apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerName }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.issuerEmailid }}
    privateKeySecretRef:
      name: {{ .Values.issuerName }}
    solvers:
    - selector: {}
      http01:
        ingress:
          class: istio