apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: divy-virtual-service
  namespace: {{ .Values.namespace.divy }}
spec:
  hosts:
  - "*"
  gateways:
  - divy-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
        - {{ .Values.hosts.cspm}} 
    route:
    - destination:
        host: nginx-service
        port:
          number: 443