apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: redis-gateway
  namespace: {{ .Values.namespace.soarcast }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 31400
      name: redis-port
      protocol: TLS
    hosts:
    - '*'
    tls:
      mode: PASSTHROUGH