apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-virtual-service
  namespace: {{ .Values.namespace.soarcast }}
spec:
  hosts:
  - "*"
  gateways:
  - redis-gateway
  tls:
  - match:
    - port: 31400
      sniHosts:
        - {{ .Values.hosts.redis}} 
    route:
    - destination:
        host: redis-service
        port:
          number: 6666