apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: soarcast-virtual-service
  namespace: {{ .Values.namespace.soarcast }}
spec:
  hosts:
  - "*"
  gateways:
  - soarcast-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
        - {{ .Values.hosts.soarcast}} 
    route:
    - destination:
        host: nginx-service
        port:
          number: 443